# Generated by Django 4.1.7 on 2023-03-31 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='roles',
            field=models.CharField(choices=[('admin', 'admin'), ('médico', 'médico'), ('investigador', 'investigador')], max_length=100),
        ),
    ]
