# Generated by Django 4.1.7 on 2023-04-21 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ultrasonido_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioexterno',
            name='userid',
            field=models.OneToOneField(db_column='UserId', default='', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personalsalud',
            name='hospitalid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='ultrasonido_app.hospital', verbose_name='Hospitales'),
        ),
        migrations.AddField(
            model_name='personalsalud',
            name='userid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicion',
            name='id_tipo_medicion',
            field=models.OneToOneField(db_column='idTipoMedicion', on_delete=django.db.models.deletion.CASCADE, to='ultrasonido_app.tipomedicion'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='idPaciente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='ultrasonido_app.paciente'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='idpac',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='ultrasonido_app.paciente'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='idreporte',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='ultrasonido_app.reporte'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='medConsulta',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='ultrasonido_app.personalsalud'),
        ),
    ]
