# Generated by Django 4.1.7 on 2023-04-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipomedicion',
            fields=[
                ('idTipoMedicion', models.AutoField(primary_key=True, serialize=False)),
                ('nombreMedicion', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name_plural': 'TiposMedicion',
                'db_table': 'TipoMedicion',
            },
        ),
    ]
