# Generated by Django 4.1.7 on 2023-04-16 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tipomedicion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('idmedicion', models.AutoField(db_column='idMedicion', primary_key=True, serialize=False)),
                ('ga', models.IntegerField(db_column='ga')),
                ('valormin', models.FloatField(blank=True, db_column='valorMin', max_length=50, null=True)),
                ('valorinter', models.FloatField(blank=True, db_column='valorMax', max_length=50, null=True)),
                ('valordev', models.FloatField(blank=True, db_column='valorDev', max_length=50, null=True)),
                ('id_tipo_medicion', models.OneToOneField(db_column='idTipoMedicion', on_delete=django.db.models.deletion.CASCADE, to='main.tipomedicion')),
            ],
            options={
                'verbose_name_plural': 'Mediciones',
                'db_table': 'Medicion',
            },
        ),
    ]
