# Generated by Django 4.1.7 on 2023-03-31 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_institucion_paciente_reporte_usuarioexterno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='medConsulta',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.personalsalud'),
        ),
    ]
