# Generated by Django 4.1.7 on 2023-05-05 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_reporte_afi'),
    ]

    operations = [
        migrations.CreateModel(
            name='FetoMedicionDiagnostico',
            fields=[
                ('idfetomediciondiagnostico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_valor', models.CharField(default='', max_length=100)),
                ('valor_med', models.CharField(db_column='valor_med', default='', max_length=100)),
                ('valor_ref', models.CharField(db_column='valor_ref', default='', max_length=100)),
                ('diagnostico', models.CharField(max_length=100)),
                ('reporte', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.reporte')),
            ],
            options={
                'verbose_name_plural': 'FetoMedicionDiagnostico',
                'db_table': 'FetoMedicionDiagnostico',
            },
        ),
    ]
