# Generated by Django 4.1.1 on 2023-04-15 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_consulta_medconsulta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('idmedicion', models.AutoField(db_column='id_medicion', primary_key=True, serialize=False)),
                ('ga', models.IntegerField(db_column='ga', null=True)),
                ('valormin', models.FloatField(blank=True, db_column='valor_min', default=0.0, null=True)),
                ('valormax', models.FloatField(blank=True, db_column='valor_max', default=0.0, null=True)),
                ('valorinter', models.FloatField(blank=True, db_column='valor_inter', default=0.0, null=True)),
            ],
            options={
                'db_table': 'Medicion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipomedicion',
            fields=[
                ('idtipomedicion', models.AutoField(db_column='id_tipo_medicion', primary_key=True, serialize=False)),
                ('nombremedicion', models.CharField(blank=True, db_column='nombre_medicion', max_length=150, null=True)),
            ],
            options={
                'db_table': 'TipoMedicion',
                'managed': False,
            },
        ),
    ]
