# Generated by Django 4.1.1 on 2023-04-15 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_medicion_tipomedicion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicion',
            options={'verbose_name_plural': 'Mediciones'},
        ),
        migrations.AlterModelOptions(
            name='tipomedicion',
            options={'verbose_name_plural': 'TiposMedicion'},
        ),
    ]
