# Generated by Django 4.1.1 on 2023-04-15 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_medicion_options_alter_tipomedicion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicion',
            name='id_tipo_medicion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.tipomedicion'),
        ),
    ]
