# Generated by Django 4.1.1 on 2023-04-15 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_medicion_id_tipo_medicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipomedicion',
            name='idtipomedicion',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipomedicion',
            name='nombremedicion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
