# Generated by Django 4.1.1 on 2023-04-15 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_tipomedicion_idtipomedicion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medicion',
        ),
    ]
